# Site settings
title:       Eduardo Coelho
email:       eduardo@educoelho.com
author:      Eduardo Coelho
description: "Eduardo Coelho's personal website."
baseurl:     ""
url:         "https://educoelho.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:   eduardocoelho
stackoverflow_id:  151883
twitter_username:  eduardo_coelho
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
paginate_path: "blog/page:num"
sass:
  compressed: true

# Plugins
plugins:
  - jekyll-paginate
